### ISSUE TITLE
Feature Request: Add compatibility with Quark's Dropoff button

### ISSUE THREAD

**Issue by faeldray** [TheTestMod/BetterCrates#1]
Crates do not appear to work with Quark's Dropoff button, which allows players to automatically deposit their inventory into storage. Adding the ability to use this button would be awesome.

Tested with:
Forge 2705
Quark 1.4-125
Better Crates 1.0.3

**Comment by TheTestMod** [comment]
I will consider this possibility :)

**Comment by Wabbit0101** [comment]
The compatibility if done via support for `IItemHandler` would also open automatic interoperability with other mods that want to prevent nesting of container-like objects. Maybe a custom `ItemBlock` that implements the IItemHandler capability instead of the vanilla version for your crate blocks.

**Comment by DoctorFTB** [comment]
For use "Dropoff" button you need change Quark config.
.minecraft/config/quark.cfg -> "chest buttons" -> S:"Dropoff Enabled Blocks" ->
Add "bettercrates:wooden_crate" for Wooden Crate.
Same with iron/copper/etc..
