### ISSUE TITLE
Disable storing crates inside crates.

### ISSUE THREAD

**Issue by calloatti** [TheTestMod/BetterCrates#2]
As the title says, disable being able to store crates inside crates.

**Comment by TheTestMod** [comment]
This will be done at 1.13.
For the 1.12.2 mod complete

**Comment by DoctorFTB** [comment]
Try 1.2.0 version.
Added.

**Comment by calloatti** [comment]
Sadly I am already on 1.14.1/fabric. It would be great if the mod got ported to 1.14.1/fabric. There are no crate mods for fabric right now.

https://minecraft.curseforge.com/mc-mods/fabric?filter-sort=2

**Comment by DoctorFTB** [comment]
Working on 1.14.2 update.

**Comment by DoctorFTB** [comment]
1.14.2 / 1.14.3 version added in Curse.
