### ISSUE TITLE
Crates Render Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [TheTestMod/BetterCrates#4]
Forge v28.1.44
Minecraft v1.14.4
Better Crates v1.0.0

Currently, Crates render incorrectly when placed underwater, it displays water flowing down it's sides.
![2019-10-11_22 46 28](https://user-images.githubusercontent.com/12000593/66694480-70d95500-ec79-11e9-9a7b-965f88eebfa7.png)

**Comment by DoctorFTB** [comment]
Try 1.14.4-1.0.1 version.

**Comment by WenXin20** [comment]
Looks good!
